version: '3'

services:
  web_interface:
    container_name: web_interface
    build: .
    networks:
      - postgresql
    ports:
      - "5009:5009"
    restart: always

  scheduler:
    container_name: scheduler
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    networks:
      - postgresql
    restart: always

networks:
  postgresql:
    name: postgresql
    external: true
